config/routes.rb
Blog::Application.routes.draw do

  devise_for :users, :skip => [:session]
  as :user do
    get '/users' => 'users#index'
    get '/lonin' => 'devise/sessions#new', :as => :new_user_session
    post '/signin' => 'devise/sessions#create', :as => :user_session
    delete '/signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end

  resources :categories
    match 'categories/:id' => 'categories#destroy', :via => :delete, :as => :admin_destroy_category

  root :to => "articles#index"
  resources :articles do
     get 'page/:page', :action => :index, :on => :collection
     resources :comments

  end

end

app/models/article.rb
class Article < ActiveRecord::Base
 extend FriendlyId
 friendly_id :title, use: [:slugged, :history]
 validates_presence_of :title, :body
 belongs_to :user
 belongs_to :category
 #has_and_belongs_to_many :categories
 has_many :comments



 #sunspot
 searchable do
  text :title, :body
  text :comments do
     comments.map(&:body)
  end
 end

 #pagination kaminari
 paginates_per 3

 #Scope
 scope :published, lambda { where("articles.published_at IS NOT NULL") }
 scope :draft, lambda { where("articles.published_at IS NULL") }
 scope :recent, lambda { published.where("articles.published_at > ?", 1.week.ago.to_date) }
 scope :where_title, lambda { |term| where("articles.title LIKE ?","%#{term}%") }



 def long_title
     "#{title} - #{published_at}"
 end

 def published?
   published_at.present?
 end

 def body_published
      "#{body} - #{published_at}"
 end

 def owned_by?(owner)
   return false unless owner.is_a?(User)
   user == owner
 end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show ]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
   if params[:search] and !params[:search].blank?
      @articles = Article.search do
       fulltext params[:search]
       paginate(:page => (params[:page] or 1), :per_page => 3)
      end.results

    else
      @articles = Article.order(published_at: :desc).page params[:page]
    end

  end

  #using concern and include

  # GET /articles/1
  # GET /articles/1.json
  def show
     #@article = current_user.articles.friendly.find(params[:id])
     @article = Article.friendly.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new

  end

  # GET /articles/1/edit
  def edit
    @article = current_user.articles.friendly.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.friendly.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article }
        format.js
        format.json { head :ok }
        #format.json { render action: 'show', status: :created, location: @article }

      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article = current_user.articles.friendly.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = current_user.articles.friendly.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.



    def set_article
      @article = Article.friendly.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      #When has_and_belongs_to_many
      params.require(:article).permit(:title, :location, :excerpt, :body, :published_at,:category_id)
      #params.require(:article).permit(:title, :location, :excerpt, :body, :published_at)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  
end

app/views/articles/_article.html.erb
<%= div_for article do %>
   <%= link_to article.title, article_path(article) %>
   <small>
     <%#When has_and_belongs_to_many %>
     <%#= article.categories[0].name %>
     <%#Below is category has many article %>
     <% if article.category %>
     <%= article.category.name %>
     <% end %>
   </small>
   <% if article.owned_by? current_user %>

   <span class='actions'>
      <small><%= link_to "Edit", edit_article_path(article), "data-no-turbolink" => true %></small>
      <small><%= link_to "Delete", article,  method: :delete, data: { confirm: 'Are you sure?' }  %></small>
   <% end %>
   </span>
   <p class="small">
 <%= simple_format(truncate(strip_tags(article.body),escape: false, length: 300) { link_to "read more",article_path(article) } ) %>
   </p>
   <hr>
<% end %>

app/views/articles/_comment.html.erb
<%= div_for comment do %>
  <h3>
   <%= comment.name %> &lt; <%= comment.email %>&gt; said:
   <span class='actions'>
     <%= link_to 'Delete', article_comment_path(:article_id => @article, :id=>comment),confirm: 'Are you sure?', method: :delete %>
   </span>
  </h3>
  <%= comment.body %>
<% end %>

app/views/articles/_form.html.erb
<%=  form_for(@article) do |f|  %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
   <div class="field">
    <label for="titleField"><%= f.label :title %></label>
    <%= f.text_field :title, :size => 33, :class=>'form-control' %>
   </div>
  </div>

  <div class="form-group">
   <div class="field">
     <label for="locationField"><%= f.label :location %></label>
     <%= f.text_field :location, :size => 37, :class=>'form-control' %>
   </div>
  </div>

  <div class="form-group">
   <div class="field">
     <%= f.label "Categories" %>
        <% @categories = Category.all %>
        <%= select_tag 'article[category_id]',options_for_select(@categories.collect{ |u| [u.name,u.id]}),:class=>"form-control" %>
   </div>
  </div>

  <div class="form-group">
   <div class="field">
     <label for="excerptField"><%= f.label :excerpt %></label>
     <%= f.text_field :excerpt, :size => 33, :class=>'form-control' %>
   </div>
  </div>

  <div class="form-group">
   <div class="field">
     <%= f.text_area  :body, :class => "tinymce", :rows=> 14, :cols => 30  %>
   </div>
  </div>

  <div class="form-group">
    <div class="field text-center">
      <lable for="publishedatField"> <%= f.label :published_at %></label>
      <%= f.datetime_select :published_at %>
    </div>
  </div>

  <div class="form-group">
  <div class="actions">
     <!--<%= submit_or_cancel(f) %>-->
     <p class="text-center"> <%= button_to "submit", new_article_path, method: :post,data: { confirm: 'Are you sure?' }, remote: true,:class=>"btn-sm btn-info" %></p>
   </div>
  </div>
<% end %>

  <%#= f.label "Categories" %><br/>
  <%# Category.all.each do |category| %>
    <%#= check_box_tag 'article[category_ids][]', category.id,
        @article.category_ids.include?(category.id), id: dom_id(category) %>
    <%#= label_tag dom_id(category), category.name, class: "check_box_label" %>
  <%# end %>

app/views/articles/_show.html.erb
<%= div_for @article do %>
 <h3>
   <%= link_to @article.title, article_path(@article) %>
   <font size=1><%= @article.published_at %></font>
   <% if @article.owned_by? current_user %>
   <span class='actions'>
     <small><%= link_to "Edit", edit_article_path(@article), data: {"no-turbolink" => true} %></small>
     <small><%= link_to "Delete", @article, :confirm => "Are you sure?", :method => :delete %></small>
   <% end %>
   </span>
 </h3>
 <%=  raw(@article.body).html_safe %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
<%= tinymce_assets %>

<%= render 'form' %>
<%= tinymce %>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render template: "articles/shared/_index" %>
<%= javascript_include_tag "fadeout" %>

app/views/articles/new.html.erb
<%= provide(:title,"New articles") %>

<div class="container" id='new'>
<%= render 'form' %>
</div>
<%= tinymce %>

app/views/articles/show.html.erb
<% provide(:title,"#{@article.title}-#{@article.category.name}") %>
<div id="show">
<%= render 'show' %>
</div>
<span class="glyphicon glyphicon-comment">Comments</span>
<hr>
<div id="comments">
  <%= render @article.comments %>
</div>
<%= link_to "new comment", new_article_comment_path(@article,:format => :js), :remote => true, :id => 'new_comment_link' %>
<%= javascript_include_tag "fadeout" %>

app/views/articles/test.html.erb
<!-- This will not be inserted -->
<div class="mceTmpl">
<table width="98%%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <th scope="col"> </th>
    <th scope="col"> </th>
  </tr>
  <tr>
    <td> </td>
    <td> </td>
  </tr>
</table></div>