config/routes.rb
Blog::Application.routes.draw do

  devise_for :users, :skip => [:session]
  as :user do
    get '/users' => 'users#index'
    get '/lonin' => 'devise/sessions#new', :as => :new_user_session
    post '/signin' => 'devise/sessions#create', :as => :user_session
    delete '/signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end

  resources :categories
    match 'categories/:id' => 'categories#destroy', :via => :delete, :as => :admin_destroy_category

  root :to => "articles#index"
  resources :articles do
     get 'page/:page', :action => :index, :on => :collection
     resources :comments

  end

end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   paginates_per 5


   has_one :profile
   has_many :articles, -> { order('published_at DESC,title ASC') },
                        :dependent => :nullify
   has_many :replies, :through => :articles, :source => :comments



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update ]
  before_action :admin_user, only: :index
  #before_action :set_user, only: [:show,:edit,:update,:destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
     if @user.save
      redirect_to articles_path, notice: 'User successfully added.'
     else
      render action: :new
      end
  end

   def edit
   end

   def update
     if @user.update(user_params)
        redirect_to articles_path, notice: 'Updated user information successfully.'
     else
        render action: 'edit'
     end
   end

   def destroy
     @user=User.find(params[:id]).destroy
      if @user.destroy
       redirect_to users_path
       flash[:success] = "User deleted"
      end
   end


 private
   def set_user
     @user = User.find(params[:id])
   end

   def user_params
     params.require(:user).permit(:email,:password,:password_confirmation)
   end

   def admin_user
     redirect_to root_path unless current_user.try(:admin?)
   end


end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    current_user.try(:admin?)
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
 <% if @user.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(@user.errors.count,"error") %>
    prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
 <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= submit_or_cancel(f) %>
  </div>
 <% end %>

app/views/users/_user.html.erb
<%= provide(:title,"Users Administration") %>
  <div class="text-center page-header">User administration</div>
  <table class="table table-bordered text-center table-hover table-condensed">
    <tr class="warning">
      <th class="text-center">Id</th>
      <th class="text-center">Email</th>
      <th class="text-center">Delete?</th>
    </tr>

  <% @users.each do |user| %>
   <tr>
   <td><%= user.id %></td>
   <td><%= user.email %></td>
     <% if current_user.try(:admin?) && user.admin != true  %>
   <td><%= link_to "delete", admin_destroy_user_path(user), method: :delete, data: {confirm: 'You sure?'} %></td>
     <% else %>
   <td>Cannot delete admin user</td>
     <% end %>
   </tr>
  <% end %>
  </table>
  </div>

app/views/users/edit.html.erb
<div class="page-header">Editing user</div>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/users/index.html.erb
<%= render 'user' %>

app/views/users/new.html.erb
<h1>New users</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>