config/routes.rb
Blog::Application.routes.draw do

  devise_for :users, :skip => [:session]
  as :user do
    get '/users' => 'users#index'
    get '/lonin' => 'devise/sessions#new', :as => :new_user_session
    post '/signin' => 'devise/sessions#create', :as => :user_session
    delete '/signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end

  resources :categories
    match 'categories/:id' => 'categories#destroy', :via => :delete, :as => :admin_destroy_category

  root :to => "articles#index"
  resources :articles do
     get 'page/:page', :action => :index, :on => :collection
     resources :comments

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged,:history]
  validates_presence_of :name, :slug
  #has_and_belongs_to_many :articles
  has_many :articles, :dependent => :destroy
  #before_destroy { articles.clear }

  default_scope lambda { order('categories.name') }

  #scope :by_id, lambda { where("categories.id = ? ",:id)}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
     #before_action :authenticate_user!
     before_action :set_category , only: [:show]


     def index
       if current_user.try(:admin?)
         @categories=Category.all


       end
     end

     def show
       articles=Article.all
       @articles=Category.friendly.find(params[:id]).articles(published_at: :desc).page params[:page]
       render template: "articles/shared/_index"
     end

     def new
       if current_user.try(:admin?)
        @category = Category.new
      else
       redirect_to(root_path)
      end

     end


     def create
       if current_user.try(:admin?)
        @category = Category.new(category_params)
         respond_to do |format|
           if @category.save
             format.html { redirect_to @category }
             format.js
             format.json { head :ok }
             #format.json { render action: 'show', status: :created, location: @article }

           else
             format.html { render action: 'new' }
             format.json { render json: @category.errors, status: :unprocessable_entity }
          end
         end
       end
     end

     def destroy
       if current_user.try(:admin?)
         @category=Category.find(params[:id]).destroy
          if @category.destroy
           redirect_to Category
           flash[:success] = "Category deleted"
          end
        end
      end


     private
     def set_category
       @category = Category.friendly.find(params[:id])
     end

     # Never trust parameters from the scary internet, only allow the white list through.
     def category_params
       params.require(:category).permit(:name,:created_at,:updated_at)

     end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%=  form_for(@category) do |f|  %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
   <div class="field">
    <label for="titleField"><%= f.label :name %></label>
    <%= f.text_field :name, :size => 33, :class=>'form-control' %>
   </div>
  </div>

  <div class="form-group">
   <div class="field">
     <label for="titleField"><%= f.label :slug %></label>

     <%= f.text_field :slug, :size => 33, :class=>'form-control' %>

   </div>
  </div>


  <div class="form-group">
  <div class="actions">
     <!--<%= submit_or_cancel(f) %>-->
     <p class="text-center"> <%= button_to "submit", categories_path, method: :post,data: { confirm: 'Are you sure?' }, remote: true,:class=>"btn-sm btn-info" %></p>
   </div>
  </div>
<% end %>

app/views/categories/index.html.erb
<% provide(:title, "Categories") %>
<% if current_user.try(:admin?) %>
  <table class="table table-bordered table-hover text-center table-condensed">
    <tr class="warning">
      <th class="text-center">Category_id</th>
      <th class="text-center">Category_name</th>
      <th class="text-center">Category_created</th>
      <th class="text-center">Category_updated</th>
      <th>Category Delete?</th>
    </tr>


  <% @categories.each do | category | %>

  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.created_at %></td>
    <td><%= category.updated_at %></td>
    <td><%= link_to "delete", admin_destroy_category_path(category[:id]), method: :delete, data: {confirm: 'You sure?'} %></td>
  </tr>
  <% end %>
  </table>
  <div class="text-center"> <%= button_to "New", new_category_path, method: :get,:class=>"btn-sm btn-info" %></div>


<% else %>
<div class="text-center warning"><h1 class="page-header ">Only Admin user can edit category </h1></div>
<% end %>

app/views/categories/new.html.erb
<% provide(:title, "New Categories") %>

<div id='new'>
<%= render 'form' %>
</div>
<%= tinymce %>