config/routes.rb
Blog::Application.routes.draw do

  devise_for :users, :skip => [:session]
  as :user do
    get '/users' => 'users#index'
    get '/lonin' => 'devise/sessions#new', :as => :new_user_session
    post '/signin' => 'devise/sessions#create', :as => :user_session
    delete '/signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end

  resources :categories
    match 'categories/:id' => 'categories#destroy', :via => :delete, :as => :admin_destroy_category

  root :to => "articles#index"
  resources :articles do
     get 'page/:page', :action => :index, :on => :collection
     resources :comments

  end

end

app/views/layouts/_category.html.erb
<!-- Get categories dynamically -->


<li class="Categories">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
               <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
               <% @categories = Category.all %>
                 <% @categories.each do |category| %>

                  <li><%= link_to category.name, category_path(category) %></li>


                  <% end %>
                  <% if admin? %>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "CategoryAdmin",Category %></li>
                  <% end %>

               </ul>
</li>

app/views/layouts/_category_footer.html.erb
<!-- Get categories dynamically -->

<li class="Categories dropup">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
               <ul class="dropdown-menu">
               <% @categories = Category.all %>
                 <% @categories.each do |category| %>

                  <li><%= link_to category.name, category_path(category) %></li>


                  <% end %>
                  <% if admin? %>
                  <li><%= link_to "CategoryAdmin",Category %></li>
                  <% end %>

               </ul>
</li>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-inverse navbar-footer" id="footer">
<!--div class="navbar navbar-inverse navbar-fixed-bottom navbar-footer" id="footer"-->

    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="collapsibleMenu">
        <ul class="nav navbar-nav navbar-right">
          <%#= link_to "New Article", new_article_path(@article,:format=>:js), remote: true,:id=>'new_post_link', "data-no-turbolink" => true %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "New Article", new_article_path, :id=>'new_post_link', :method => 'get', "data-no-turbolink" => true %></li>
          <% if signed_in? %>
           <li><%= link_to "User Edit", edit_user_registration_path(current_user) %> </li>
           <li><%= link_to "Logout(#{current_user.email})", destroy_user_session_path, method: :delete %></li>
           <% if admin? %>
             <li><%= link_to "Users", users_path %></li>
           <% end %>
          <% else %>
           <li><%= link_to "Login", new_user_session_path %></li>
           <li><%= link_to "Register", new_user_registration_path %> </li>
          <% end %>
          <!-- rendering category -->
          <%= render 'layouts/category_footer' %>
        </ul>
       </div>
     </div>
   </div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top" id="header">
<!--div class="navbar navbar-static-top" id="header"> -->

    <div class="container-fluid">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
      <div class="collapse navbar-collapse"  id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%#= link_to "New Article", new_article_path(@article,:format=>:js), remote: true,:id=>'new_post_link', "data-no-turbolink" => true %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "New Article", new_article_path, :id=>'new_post_link', :method => 'get', "data-no-turbolink" => true %></li>
          <% if signed_in? %>
           <li><%= link_to "Edit", edit_user_registration_path(current_user) %> </li>
           <li><%= link_to "Logout(#{current_user.email})", destroy_user_session_path, method: :delete %></li>
           <% if admin? %>
             <li><%= link_to "Users", users_path %></li>
           <% end %>
          <% else %>
           <li><%= link_to "Login", new_user_session_path %></li>
           <li><%= link_to "Register", new_user_registration_path %> </li>
          <% end %>
          <!-- rendering category -->
          <%= render 'layouts/category' %>
        </ul>
          <%= render 'layouts/search' %>
       </div>
     </div>
   </div>

app/views/layouts/_search.html.erb
<!--glyphicon glyphicon-search-->
          <form class="navbar-form navbar-right" role="search" action="/articles" accept-charset="UTF-8" method="get", validate="true">
             <div class="form-group has-feedback">
              <input name="utf8" type="hidden" />
              <input type="text" class="form-control" placeholder="search" name="search" id="search">
              <i class="glyphicon glyphicon-search form-control-feedback"></i>
             </div>
          </form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>




  <div class="container"  id="main">
    <center><%= content_tag(:p, notice, :class => 'notice') if notice.present? %></center>
    <%= content_tag(:p, alert, :class => 'alert') if alert.present? %>
    <%= yield %>
  </div>

  <div class="modal fade" id="searchModal">
       <div class="modal-body">
        <%= render 'layouts/search' %>
       </div>
  </div>


  <%= render 'layouts/footer' %>
</body>
</html>